### ISSUE TITLE
亟待解决的问题

### ISSUE THREAD

**Issue by luckyadam** [o2team/athena#1]
- [x] 将sass编译替换为使用node-sass
- [x] 安装提速
- [x] 精简包依赖
- [x] 编译提速

**Comment by luckyadam** [comment]
- [ ] 错误信息提示优化
- [ ] 文件出错serve不中断

**Comment by geraldlrh** [comment]
用啥sass，low

**Comment by luckyadam** [comment]
@geraldlrh 你们用啥

**Comment by geraldlrh** [comment]
less postcss

**Comment by jincdream** [comment]
sass 编译环境的安装时很头痛的问题。。

**Comment by luckyadam** [comment]
@jincdream node-sass有提供各个平台编译好的包，安装起来不需要再编译，应该好很多~

**Comment by jincdream** [comment]
在windows下安装node-sass需要依赖什么vc＋＋ 之类的。。

**Comment by XIAOGUIGUI** [comment]
![ddcf23f8-9cc1-4f9c-893c-8cf63cb4148e](https://cloud.githubusercontent.com/assets/8243283/14662820/80f13960-06ec-11e6-8c2c-02f65f8d6b35.png)
为什么都是执行两遍？

**Comment by XIAOGUIGUI** [comment]
为什么这个会报错误。
![Uploading EE48E549-F96E-464A-A803-E659C00B8465.png…]()

**Comment by Manjiz** [comment]
@jincdream 可以通过修改install.js或下载vender包就可以了，不用再编译的
