### ISSUE TITLE
组件归属问题

### ISSUE THREAD

**Issue by Secbone** [o2team/athena#13]
组件在创建时是基于module创建的，但是在打包合并的时候，却是基于页面去区分的。

也就是公共组件会在不同页面里被重复引用并且分别打包，有点迷

是否应该把公共组件打包到static里面去？

**Comment by luckyadam** [comment]
@Secbone 这个应该没必要的，公共组件有公共模块来承载，供其他模块来调用

**Comment by luckyadam** [comment]
@Secbone 可以对现有目录结构和编译流程进行适当调整

**Comment by Secbone** [comment]
OK~
