### ISSUE TITLE
sass 监听更新问题

### ISSUE THREAD

**Issue by Secbone** [o2team/athena#14]
当页面引用自建的 main.scss 文件，在 main.scss 改动时，页面会刷新并载入新样式，
但是当在 main.scss 文件中 import 另外一个自建样式文件，如 other.scss，当修改 other.scss 文件时，页面有刷新，但是并没有编译载入新的样式，而是需要在 main.scss 改变时才重新编译出新样式

**Comment by luckyadam** [comment]
下一个版本修复。暂时可以通过清除sass缓存 ath clear -s 然后重新serve解决。

**Comment by luckyadam** [comment]
https://github.com/o2team/athena/commit/566e84cfcd32161cabf79920140dc9e35efca842

**Comment by luckyadam** [comment]
已修复，请更新到最新版本使用~ @Secbone
