### ISSUE TITLE
静态资源添加版本号功能

### ISSUE THREAD

**Issue by Secbone** [o2team/athena#16]
可以配置为静态资源添加版本号，以便于强制刷新 IDC 资源

**Comment by luckyadam** [comment]
文件md5戳现在不能满足么 @Secbone

**Comment by Secbone** [comment]
是因为会出现IDC缓存错误，但实际上文件并没有修改，所以MD5不会变，所以希望能有一个版本号的东西，可以在MD5不变的情况下，手动刷新缓存。 比如类似`ath clear`以后，再build的时候，生成新的MD5
:)

**Comment by luckyadam** [comment]
@Secbone md5只随内容变化而变化，增加一个时间戳配置能否满足需求？

**Comment by Secbone** [comment]
已使用  `needTimestamp` 配置  :)
