### ISSUE TITLE
static静态资源名称中带多个点时无法被引用

### ISSUE THREAD

**Issue by Manjiz** [o2team/athena#21]
static的资源名字中带多个点的不能被引用到，改成下划线就行了，比如：<%= getJS('zepto.detect.js', 'gb') %> 没有引进来，当把文件名以及static-conf.js中的配置名字都改成下划线形式 `zepto_detect.js` 就正常了

**Comment by luckyadam** [comment]
已fix~

**Comment by luckyadam** [comment]
已fix~
