### ISSUE TITLE
请问这个项目和百度的fis相比有什么优势，两者区别在哪？

### ISSUE THREAD

**Issue by pdap** [o2team/athena#24]

**Comment by ummo** [comment]
两家各自造轮子啊，40%为了适应自己业务的特殊需求，30%为了升值加薪，30%为了江湖地位

**Comment by pdap** [comment]
@ummo  原来如此啊。。。。

**Comment by mircode** [comment]
确实很百度的FIS很像，要是能提供RiotJS中的预编译功就好了。能够直接将模板语言输出为HTML，提供线下编译的的机制。

**Comment by piaer** [comment]
求问：这个解决方案能否把ES6转化为ES5

**Comment by luckyadam** [comment]
@piaer 可以呀
