### ISSUE TITLE
执行ath init，然后不管是否输入了用户名，回车之后都会卡死，没有任何响应

### ISSUE THREAD

**Issue by chenxiaochun** [o2team/athena#3]
![qq 20160314153147](https://cloud.githubusercontent.com/assets/1744713/13737676/07a02eae-e9fa-11e5-915e-0a370e934daa.jpg)

**Comment by luckyadam** [comment]
好的，我看看
貌似是[inquire](https://github.com/SBoudrias/Inquirer.js)对mingw支持不够好，windows自带的cmd和windows powershell可以运行~

**Comment by chenxiaochun** [comment]
ok，换成cmd了，现在貌似正常了
