### ISSUE TITLE
关于资源定位 __uri 的疑问

### ISSUE THREAD

**Issue by leeenx** [o2team/athena#42]
https://github.com/o2team/athena#资源定位

 这里提到了使用 __uri `可以自动化将资源引用链接替换成配置好的目标地址`。我的理解是引用 __uri(1.jpg) 后，athena 会自动帮我把引用的hash化后的资源 1_xxxxxxxx.jpg。然而，我的实际操作结果是，__uri后的图片是 1.jpg，也就是 __uri 没起到作用？

------我是在js中使用 __uri()。html的<%= __uri() %> 还未尚试

**Comment by luckyadam** [comment]
待我更新下文档~
