### ISSUE TITLE
module-conf.js compress 缺省值补全

### ISSUE THREAD

**Issue by leeenx** [o2team/athena#72]
目前版本，compress 选项已经默认在 module-conf.js 上显示了。不过，原来的 transform 压缩问题仍未得到解决。麻烦在下一个版本使用以下配置：

compress: {
      css: {
        mergeRules: false,
        mergeIdents: false,
        reduceIdents: false,
        discardUnused: false,
        minifySelectors: false, 
        reduceTransforms: false
      },
      js: {
        mangle:{except : ['require', 'exports', 'seajs', 'module']}
      }
    },

**Comment by luckyadam** [comment]
已加入到默认配置！
